---
title: Publications
listing:
  - id: articles
    contents: "articles/*/index.qmd"
    sort: "date desc"
    template: "../html/publications/listing.ejs"
    categories: true
  - id: conference-papers
    contents: "conference-papers/*/index.qmd"
    sort: "date desc"
    template: "../html/publications/listing.ejs"
    categories: true
html:
  css: styles.scss
page-layout: full
include-back-link: false
toc-location: right
---

My research has focused on the digitisation of chemistry. Bridging the gap between the virtual and physical worlds, by integrating AI, cloud computing, robotics, and advanced computing technologies to accelerate scientific discovery.

## Articles

<script>
// JavaScript code here
function convertBibtex(bibtex) {

var author_name = "Thakkar, Amol"

  // Parse the BibTeX input
  var parser = new BibtexParser();
  var entries = parser.parse(bibtex);
console.log(entries)
console.log(entries.length)
  // Generate the ACS HTML output
  var html = "";
  for (var i = 0; i < entries.length; i++) {
    console.log(i)
    var entry = entries[i];
    console.log(entry)
    html += "<p><li>";
    if (entry.hasOwnProperty("author")) {
    var authors = entry.author.split(/(?<!\{) and |(?<!\{)&/);
    var formattedAuthors = authors.map(function(author) {
        return author.trim();
    });
    
    for (var k = 0; k < formattedAuthors.length; k++) {
        if (formattedAuthors[k] === author_name) {
        html += "<b>" + formattedAuthors[k] + "</b>";
        } else {
        html += formattedAuthors[k];
        }
        
        if (i < formattedAuthors.length - 1) {
        html += "; ";
        } else {
        html += ". ";
        }
    }
    }
    
    if (entry.hasOwnProperty("title")) {
      html += entry.title + ". ";
    }
    if (entry.hasOwnProperty("journal")) {
      html += "<i>" + entry.journal + "</i>, ";
    }
    if (entry.hasOwnProperty("year")) {
      html += entry.year + ".";
    }
    if (entry.hasOwnProperty("doi")) {
      html += "<br> doi: <a href='https://doi.org/" + entry.doi + "'>" + entry.doi + "</a>.";
    }
    html += "</li></p>";
    console.log(html)
  }
    
  return html;
}

function BibtexParser() {
  this.parse = function(bibtex) {
    var entries = [];
    var lines = bibtex.split("\n");

    var currentEntry = {};
    for (var i = 0; i < lines.length; i++) {
      var line = lines[i].trim();
      if (line.startsWith("@")) {
        // New entry
        if (Object.keys(currentEntry).length > 0) {
          entries.push(currentEntry);
          currentEntry = {};
        }
        var entryType = line.match(/@(\w+)/)[1].toLowerCase();
        currentEntry["entryType"] = entryType;
      } else if (line.startsWith("}")) {
        // End of entry
        entries.push(currentEntry);
        currentEntry = {};
      } else if (line.includes("=")) {
        // Field
        var field = line.match(/(\w+)\s*=\s*{([^}]*)}/);
        if (field) {
          var fieldName = field[1].toLowerCase();
          var fieldValue = field[2];
          currentEntry[fieldName] = fieldValue;
        }
      }
    }

    return entries;
  };
}

window.addEventListener('DOMContentLoaded', function() {
      var bibtex = `
@article{thakkar_datasets_2020,
	title = {Datasets and their influence on the development of computer assisted synthesis planning tools in the pharmaceutical domain},
	volume = {11},
	url = {https://pubs.rsc.org/en/content/articlelanding/2020/sc/c9sc04944d},
	doi = {https://doi.org/10.1039/C9SC04944D},
	number = {1},
	journal = {Chemical science},
	author = {Thakkar, Amol and Kogej, Thierry and Reymond, Jean-Louis and Engkvist, Ola and Bjerrum, Esben Jannik},
	year = {2020},
	note = {Publisher: Royal Society of Chemistry},
	pages = {154--168},
}

@inproceedings{thakkar_neural_2019,
	title = {Neural Network Guided Tree-Search Policies for Synthesis Planning},
	url = {https://link.springer.com/chapter/10.1007/978-3-030-30493-5_64},
	doi = {https://doi.org/10.1007/978-3-030-30493-5_64},
	booktitle = {International Conference on Artificial Neural Networks},
	publisher = {Springer International Publishing Cham},
	author = {Thakkar, Amol and Bjerrum, Esben Jannik and Engkvist, Ola and Reymond, Jean-Louis},
	year = {2019},
	pages = {721--724},
}

@article{sieffert_modelling_2018,
	title = {Modelling uranyl chemistry in liquid ammonia from density functional theory},
	volume = {54},
	url = {https://pubs.rsc.org/en/content/articlelanding/2018/cc/c8cc05382k/unauth},
	doi = {https://doi.org/10.1039/C8CC05382K},
	number = {74},
	journal = {Chemical Communications},
	author = {Sieffert, Nicolas and Thakkar, Amol and Bühl, Michael},
	year = {2018},
	note = {Publisher: Royal Society of Chemistry},
	pages = {10431--10434},
}

@article{thakkar_ring_2020,
	title = {“Ring breaker”: neural network driven synthesis prediction of the ring system chemical space},
	volume = {63},
	url = {https://pubs.acs.org/doi/full/10.1021/acs.jmedchem.9b01919},
	doi = {https://doi.org/10.1021/acs.jmedchem.9b01919},
	number = {16},
	journal = {Journal of medicinal chemistry},
	author = {Thakkar, Amol and Selmi, Nidhal and Reymond, Jean-Louis and Engkvist, Ola and Bjerrum, Esben Jannik},
	year = {2020},
	note = {Publisher: American Chemical Society},
	pages = {8791--8808},
}

@article{bjerrum_artificial_2020,
	title = {Artificial Applicability Labels for Improving Policies in Retrosynthesis Prediction},
	volume = {2},
	url = {https://iopscience.iop.org/article/10.1088/2632-2153/abcf90/meta},
	doi = {10.1088/2632-2153/abcf90},
	number = {1},
	journal = {Machine Learning: Science and Technology},
	author = {Bjerrum, Esben Jannik and Thakkar, Amol and Engkvist, Ola},
	year = {2020},
	note = {Publisher: Machine Learning: Science and Technology},
}

@article{genheden_aizynthfinder_2020,
	title = {AiZynthFinder: a fast, robust and flexible open-source software for retrosynthetic planning},
	volume = {12},
	url = {https://link.springer.com/article/10.1186/s13321-020-00472-1},
	doi = {https://doi.org/10.1186/s13321-020-00472-1},
	number = {1},
	journal = {Journal of cheminformatics},
	author = {Genheden, Samuel and Thakkar, Amol and Chadimová, Veronika and Reymond, Jean-Louis and Engkvist, Ola and Bjerrum, Esben},
	year = {2020},
	note = {Publisher: Springer International Publishing Cham},
	pages = {70},
}

@article{sumner_levenshtein_2020,
	title = {Levenshtein augmentation improves performance of smiles based deep-learning synthesis prediction},
	url = {https://chemrxiv.org/engage/chemrxiv/article-details/60c74d89702a9b293c18b884},
	doi = {10.26434/chemrxiv.12562121.v2},
	journal = {ChemRxiv},
	author = {Sumner, Dean and He, Jiazhen and Thakkar, Amol and Engkvist, Ola and Bjerrum, Esben Jannik},
	year = {2020},
}

@article{johansson_ai-assisted_2019,
	title = {AI-assisted synthesis prediction},
	volume = {32},
	url = {https://www.sciencedirect.com/science/article/abs/pii/S1740674920300020},
	doi = {https://doi.org/10.1016/j.ddtec.2020.06.002},
	journal = {Drug Discovery Today: Technologies},
	author = {Johansson, Simon and Thakkar, Amol and Kogej, Thierry and Bjerrum, Esben and Genheden, Samuel and Bastys, Tomas and Kannas, Christos and Schliep, Alexander and Chen, Hongming and Engkvist, Ola},
	year = {2019},
	note = {Publisher: Elsevier},
	pages = {65--72},
}

@article{david_molecular_2020,
	title = {Molecular representations in AI-driven drug discovery: a review and practical guide},
	volume = {12},
	url = {https://link.springer.com/article/10.1186/s13321-020-00460-5},
	doi = {https://doi.org/10.1186/s13321-020-00460-5},
	number = {1},
	journal = {Journal of Cheminformatics},
	author = {David, Laurianne and Thakkar, Amol and Mercado, Rocío and Engkvist, Ola},
	year = {2020},
	note = {Publisher: Springer International Publishing Cham},
	pages = {56},
}

@article{thakkar_retrosynthetic_2021,
	title = {Retrosynthetic accessibility score (RAscore)–rapid machine learned synthesizability classification from AI driven retrosynthetic planning},
	volume = {12},
	url = {https://pubs.rsc.org/en/content/articlelanding/2021/sc/d0sc05401a},
	doi = {https://doi.org/10.1039/D0SC05401A},
	number = {9},
	journal = {Chemical science},
	author = {Thakkar, Amol and Chadimová, Veronika and Bjerrum, Esben Jannik and Engkvist, Ola and Reymond, Jean-Louis},
	year = {2021},
	note = {Publisher: Royal Society of Chemistry},
	pages = {3339--3349},
}

@article{thakkar_artificial_2021,
	title = {Artificial intelligence and automation in computer aided synthesis planning},
	volume = {6},
	url = {https://pubs.rsc.org/en/content/articlelanding/2021/re/d0re00340a},
	doi = {10.1039/D0RE00340A},
	number = {1},
	journal = {Reaction chemistry \& engineering},
	author = {Thakkar, Amol and Johansson, Simon and Jorner, Kjell and Buttar, David and Reymond, Jean-Louis and Engkvist, Ola},
	year = {2021},
	note = {Publisher: Royal Society of Chemistry},
	pages = {27--51},
}

@article{thakkar_how_2021,
	title = {How AI for synthesis can help tackle challenges in molecular discovery: Medicinal chemistry and chemical biology highlights},
	volume = {75},
	url = {https://www.chimia.ch/chimia/article/view/2021_677},
	doi = {https://doi.org/10.2533/chimia.2021.677},
	number = {7-8},
	journal = {Chimia},
	author = {Thakkar, Amol and Schwaller, Philippe},
	year = {2021},
	pages = {677--677},
}

@phdthesis{thakkar_computer_nodate,
	type = {PhD Thesis},
	title = {Computer Aided Synthesis Prediction to Enable Augmented Chemical Discovery and Chemical Space Exploration},
	url = {https://core.ac.uk/download/pdf/521342892.pdf},
	school = {Universität Bern},
	author = {Thakkar, Amol and Reymond, Jean-Louis},
}

@article{thakkar_automatic_2022,
	title = {Automatic Extraction of Reaction Templates for Synthesis Prediction},
	volume = {76},
	url = {https://chimia.ch/chimia/article/view/2022_294},
	doi = {https://doi.org/10.2533/chimia.2022.294},
	number = {4},
	journal = {Chimia},
	author = {Thakkar, Amol and Reymond, Jean-Louis},
	year = {2022},
	pages = {294--297},
}

@inproceedings{thakkar_augmented_2022,
	title = {Augmented disconnection aware retrosynthesis to facilitate user interaction},
	url = {https://research.ibm.com/publications/augmented-disconnection-aware-retrosynthesis-to-facilitate-user-interaction},
	booktitle = {American {Chemical} {Society} ({ACS}) {Fall} {Meeting}},
	author = {Thakkar, Amol and Byekwaso, Andrea Antonia and Schwaller, Philippe and Vaucher, Alain and Toniato, Alessandra and Laino, Teodoro},
	year = {2022},
}

@article{thakkar_unbiasing_2023,
	title = {Unbiasing retrosynthesis language models with disconnection prompts},
	volume = {9},
	url = {https://pubs.acs.org/doi/full/10.1021/acscentsci.3c00372},
	doi = {https://doi.org/10.1021/acscentsci.3c00372},
	number = {7},
	journal = {ACS Central Science},
	author = {Thakkar, Amol and Vaucher, Alain C and Byekwaso, Andrea and Schwaller, Philippe and Toniato, Alessandra and Laino, Teodoro},
	year = {2023},
	note = {Publisher: American Chemical Society},
	pages = {1488--1498},
}

@article{kannas_rxnutilscheminformatics_2022,
	title = {Rxnutils–a cheminformatics python library for manipulating chemical reaction data},
	url = {https://chemrxiv.org/engage/chemrxiv/article-details/62ff6e3d1945ad5634dee451},
	doi = {10.26434/chemrxiv-2022-wt440-v2},
	author = {Kannas, Christos and Thakkar, Amol and Bjerrum, Esben and Genheden, Samuel},
	year = {2022},
}

@inproceedings{thakkar_disconnection_2022,
	title = {Disconnection Aware Steering of Retrosynthesis Transformer to Facilitate Materials Design},
	url = {https://research.ibm.com/publications/disconnection-aware-steering-of-retrosynthesis-transformer-to-facilitate-materials-design},
	booktitle = {Materials Research Society (MRS) Fall Meeting},
	author = {Thakkar, Amol and Byekwaso, Andrea Antonia and Vaucher, Alain and Schwaller, Philippe and Toniato, Alessandra and Laino, Teodoro},
	year = {2022},
}

@article{cretu_standardization_2022,
	title = {Standardization of chemical compounds using language modeling},
	url = {https://chemrxiv.org/engage/chemrxiv/article-details/636927c0b58850fd35408fbc},
	doi = {10.26434/chemrxiv-2022-14ztf},
	author = {Cretu, Miruna T and Toniato, Alessandra and Vaucher, Alain C and Thakkar, Amol and Debabeche, Amin and Laino, Teodoro},
	year = {2022},
}

@article{chakraborty_data-driven_2022,
	title = {Data-driven Reaction Template Fingerprints},
	url = {https://chemrxiv.org/engage/chemrxiv/article-details/637b92493551190cc33b635f},
	doi = {10.26434/chemrxiv-2022-4kzp1},
	journal = {ChemRxiv},
	author = {Chakraborty, Anubhab and Thakkar, Amol and Vaucher, Alain C and Laino, Teodoro},
	year = {2022},
}

@article{cretu_tools_2023,
	title = {Tools for Synthesis Planning, Automation, and Analytical Data Analysis},
	volume = {77},
	url = {https://www.chimia.ch/chimia/article/view/2023_17},
	doi = {https://doi.org/10.2533/chimia.2023.17},
	number = {1/2},
	journal = {Chimia},
	author = {Cretu, Miruna and Alberts, Marvin and Chakraborty, Anubhab and Leonov, Artem and Thakkar, Amol and Laino, Teodoro},
	year = {2023},
	pages = {17--21},
}

@article{cretu_standardizing_2023,
	title = {Standardizing chemical compounds with language models},
	volume = {4},
	url = {https://iopscience.iop.org/article/10.1088/2632-2153/ace878/meta},
	doi = {10.1088/2632-2153/ace878},
	number = {3},
	journal = {Machine Learning: Science and Technology},
	author = {Cretu, Miruna T and Toniato, Alessandra and Thakkar, Amol and Debabeche, Amin A and Laino, Teodoro and Vaucher, Alain C},
	year = {2023},
	note = {Publisher: IOP Publishing},
	pages = {035014},
}

@inproceedings{thakkar_neute-neural_2023,
	title = {NeuTE-Neural Template Extraction},
	url = {https://research.ibm.com/publications/neute-neural-template-extraction},
	booktitle = {American Chemical Society (ACS) Spring Meeting},
	author = {Thakkar, Amol and Laino, Teodoro},
	year = {2023},
}

@inproceedings{thakkar_creating_2023,
	title = {Creating labs that learn through automated data management},
	url = {https://research.ibm.com/publications/creating-labs-that-learn-through-automated-data-management},
	booktitle = {American Chemical Society (ACS) Fall Meeting},
	author = {Thakkar, Amol and Giovannini, Andrea and Manica, Matteo and Vaucher, Alain and Ruch, Patrick and Laino, Teodoro},
	year = {2023},
}

@inproceedings{ruch_new_2023,
	title = {A new era of collaborative experimentation enabled by multi-cloud and AI foundation models},
	url = {https://research.ibm.com/publications/a-new-era-of-collaborative-experimentation-enabled-by-multi-cloud-and-ai-foundation-models},
	booktitle = {Future Labs Live},
	author = {Ruch, Patrick and Vaucher, Alain and Thakkar, Amol and Giovannini, Andrea and Foncubierta, Antonio and Christofidellis, Dimitrios and Zipoli, Federico and Born, Jannis and Cadow, Joris and Rapsomaniki, Marianna and {others}},
	year = {2023},
}

@inproceedings{thakkar_using_2023,
	title = {Using Foundation Models to Promote Digitization and Reproducibility in Scientific Experimentation},
	url = {https://openreview.net/forum?id=A28gzFJd28},
	booktitle = {NeurIPS 2023 AI for Science Workshop},
	author = {Thakkar, Amol and Giovannini, Andrea and Foncubierta, Antonio and Baldassari, Carlo and Christofidellis, Dimitrios and Zipoli, Federico and Gabrieli, Gianmarco and Born, Jannis and Graziani, Mara and Alberts, Marvin and {others}},
	year = {2023},
}

@article{thakkar_neural_2024,
	title = {Neural Template Extraction-Learning the Language of ßSMIRKS},
	url = {https://chemrxiv.org/engage/chemrxiv/article-details/664de6a821291e5d1df74ac0},
	doi = {10.26434/chemrxiv-2024-bmk3w},
	journal = {ChemRxiv},
	author = {Thakkar, Amol and Laino, Teodoro},
	year = {2024},
}

@inproceedings{ruch_multimodal_2024,
	title = {Multimodal foundation models for more reproducible scientific experimentation and data capture},
	url = {https://research.ibm.com/publications/multimodal-foundation-models-for-more-reproducible-scientific-experimentation-and-data-capture},
	booktitle = {Future {Labs} {Live}},
	author = {Ruch, Patrick and Gabrieli, Gianmarco and Morales, Irina Espejo and Christofidellis, Dimitrios and Graziani, Mara and Giovannini, Andrea and Zipoli, Federico and Thakkar, Amol and Foncubierta, Antonio and Manica, Matteo and {others}},
	year = {2024},
}

@article{gabrieli_activity_2025,
	title = {Activity recognition in scientific experimentation using multimodal visual encoding},
	url = {http://dx.doi.org/10.1039/D4DD00287C},
	doi = {10.1039/D4DD00287C},
	abstract = {Capturing actions during scientific experimentation is a cornerstone of reproducibility and collaborative research. While large multimodal models hold promise for automatic action (or activity) recognition, their ability to provide real-time captioning of scientific actions remains to be explored. Leveraging multimodal egocentric videos and model finetuning for chemical experimentation, we study the action recognition performance of Vision Transformer (ViT) encoders coupled either to a multi-label classification head or a pretrained language model, as well as that of two state-of-the-art vision-language models, Video-LLaVA and X-CLIP. Highest fidelity was achieved for models coupled with trained classification heads or a fine-tuned language model decoder, for which individual actions were recognized with F1 scores between 0.29–0.57 and action sequences were transcribed at normalized Levenshtein ratios of 0.59–0.75, while inference efficiency was highest for models based on ViT encoders coupled to classifiers, yielding a 3-fold relative inference speed-up on GPU over language-assisted models. While models comprising generative language components were penalized in terms of inference time, we demonstrate that augmenting egocentric videos with gaze information increases the F1 score (0.52 → 0.61) and Levenshtein ratio (0.63 → 0.72, p = 0.047) for the language-assisted ViT encoder. Based on our evaluation of preferred model configurations, we propose the use of multimodal models for near real-time action recognition in scientific experimentation as viable approach for automatic documentation of laboratory work.},
	journal = {Digital Discovery},
	author = {Gabrieli, Gianmarco and Espejo Morales, Irina and Christofidellis, Dimitrios and Graziani, Mara and Giovannini, Andrea and Zipoli, Federico and Thakkar, Amol and Foncubierta, Antonio and Manica, Matteo and Ruch, Patrick W.},
	year = {2025},
	note = {Publisher: RSC},
	pages = {--},
}

@article{carrel2025exploring,
  title={Exploring Simple Drug Scaffolds from the Generated Database Chemical Space Reveals a Chiral Bicyclic Azepane with Potent Neuropharmacology},
  author={Carrel, Aline and Yiannakas, Adonis and Roukens, Jaap-Jan and Reynoso-Moreno, Ines and Orsi, Markus and Thakkar, Amol and Arus-Pous, Josep and Pellegata, Daniele and Gertsch, Jürg and Reymond, Jean-Louis},
  journal={Journal of Medicinal Chemistry},
  year={2025},
  publisher={American Chemical Society}
}

`;

      document.getElementById("biblio").innerHTML = convertBibtex(bibtex);
    });
</script>

<ol>
<div id="biblio"></div>
</ol>